---
# tasks file for roles/common

- name: Setup the repo file
  copy:      
    src: open_three-tier-app.repo
    dest: /etc/yum.repos.d/open_three-tier-app.repo
  tags: ['never','setup']

- name: Remove the repo file
  file:
    state: absent
    path: /etc/yum.repos.d/open_three-tier-app.repo
  tags: ['never','cleanup']

- name: Remove base tools and three tier app packages
  package:
    name: "{{ three_tier_packages }}"
    state: absent
  tags: ['never','cleanup']

- name: Remove index.html
  file:
    path: /tmp/index.html
    state: absent
  tags: ['never','cleanup']