---
# tasks file for roles/postgres
  
- name: Install Postgres
  package:
    state: present 
    name: postgresql-server

- name: Check if File Exists
  stat:
      path: /var/lib/pgsql/data/PG_VERSION
  register: psql_stat_result
  
- name: Initialise DB
  command: postgresql-setup initdb
  when: not psql_stat_result.stat.exists
  notify: 
    - enable postgresql
    - start postgresql